# Generated by Django 5.0.1 on 2024-01-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_bireports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bireports",
            name="report_link",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
