# Generated by Django 5.0.1 on 2024-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_bireports_report_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bireports",
            name="report_link",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
