# Generated by Django 5.0.1 on 2024-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_bireports_report_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="bireports",
            name="report_department",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
