# Generated by Django 5.0.1 on 2024-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_bireports_report_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmembers",
            name="staff_title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
